engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
exclude_paths:
- "hooks/*"
- "res/*"
- "scss/*"
- "tests/*"
- "gulpfile.js"
